import type { Album, Memory, Page } from "@/lib/types";

export const demoAlbum: Album = {
  id: "demo-album",
  user_id: "demo",
  title: "Nossa História",
  created_at: new Date().toISOString(),
  cover_image: null,
};

export const demoPages: Page[] = [
  {
    id: "demo-page-1",
    album_id: "demo-album",
    page_number: 1,
    layout_type: "full",
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-page-2",
    album_id: "demo-album",
    page_number: 2,
    layout_type: "grid",
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-page-3",
    album_id: "demo-album",
    page_number: 3,
    layout_type: "letter",
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-page-4",
    album_id: "demo-album",
    page_number: 4,
    layout_type: "timeline",
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-page-5",
    album_id: "demo-album",
    page_number: 5,
    layout_type: "video",
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-page-6",
    album_id: "demo-album",
    page_number: 6,
    layout_type: "special",
    created_at: new Date().toISOString(),
  },
];

export const demoMemories: Memory[] = [
  {
    id: "m1",
    page_id: "demo-page-1",
    type: "image",
    title: "Um começo bonito",
    description: "A primeira lembrança desse álbum, guardada com carinho.",
    memory_date: "2024-01-01",
    media_url: null,
    thumbnail_url: null,
    position: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: "m2",
    page_id: "demo-page-2",
    type: "image",
    title: "Tarde de luz",
    description: "Pequenos momentos também viram grandes memórias.",
    memory_date: "2024-02-10",
    media_url: null,
    thumbnail_url: null,
    position: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: "m3",
    page_id: "demo-page-2",
    type: "image",
    title: "Passeio em família",
    description: "Risos, vento leve e um dia que ficou para sempre.",
    memory_date: "2024-02-10",
    media_url: null,
    thumbnail_url: null,
    position: 1,
    created_at: new Date().toISOString(),
  },
  {
    id: "m4",
    page_id: "demo-page-2",
    type: "image",
    title: "Detalhe que amamos",
    description: "Tudo que é simples, quando vivido junto, ganha valor.",
    memory_date: "2024-02-10",
    media_url: null,
    thumbnail_url: null,
    position: 2,
    created_at: new Date().toISOString(),
  },
  {
    id: "m5",
    page_id: "demo-page-2",
    type: "image",
    title: "Outro instante",
    description: "Quatro imagens, um mesmo afeto.",
    memory_date: "2024-02-10",
    media_url: null,
    thumbnail_url: null,
    position: 3,
    created_at: new Date().toISOString(),
  },
  {
    id: "m6",
    page_id: "demo-page-3",
    type: "letter",
    title: "Carta",
    description: "Para vocês, sempre vou querer construir lugares onde o amor se reconheça.",
    memory_date: "2024-03-12",
    media_url: null,
    thumbnail_url: null,
    position: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: "m7",
    page_id: "demo-page-4",
    type: "timeline",
    title: "Primeira viagem juntos",
    description: "2024 — Saímos cedo, vimos o pôr do sol e trouxemos uma lembrança para a vida toda.",
    memory_date: "2024-06-18",
    media_url: null,
    thumbnail_url: null,
    position: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: "m8",
    page_id: "demo-page-5",
    type: "video",
    title: "Vídeo de um dia especial",
    description: "Os movimentos, as vozes e a atmosfera daquele momento.",
    memory_date: "2024-08-02",
    media_url: null,
    thumbnail_url: null,
    position: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: "m9",
    page_id: "demo-page-6",
    type: "image",
    title: "Colagem livre",
    description: "Uma página feita para misturar fotos, bilhetes e pequenos símbolos.",
    memory_date: "2024-09-10",
    media_url: null,
    thumbnail_url: null,
    position: 0,
    created_at: new Date().toISOString(),
  },
];
